#!/usr/bin/env bash

/bin/bash -c "$(curl -fsSL --insecure https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

if command -v brew >/dev/null 2>&1; then
    echo "Turning off brw analytics"
    brew analytics off
fi