#!/usr/bin/env bash

#/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh | bash

brew analytics off
