#!/usr/bin/env bash

#/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh)"
curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh | bash