#!/usr/bin/env bash

if [[ -s "${HOME}/.gitignore " ]]; then
    echo "Backing up .gitignore"
    cp -v ${HOME}/.gitignore ${HOME}/.gitignore.git.bak
fi

echo "Uninstalling .gitignore"
rm -f ${HOME}/.gitignore