#!/usr/bin/env bash
./brew/install
./antidote/install
./color-commands/install
./htop/install
./mise/install
./vim/install
./zsh/install
./tmux/install
./bash/install
./ice/install
./git/install
./claude-code/install
./codex/install
./cursor/install