#!/usr/bin/env bash
BASE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

${BASE_DIR}/bash/install
${BASE_DIR}/zsh/install
${BASE_DIR}/brew/install

${BASE_DIR}/antidote/install
${BASE_DIR}/mise/install
${BASE_DIR}/bat/install
${BASE_DIR}/claude-code/install
${BASE_DIR}/codex/install
${BASE_DIR}/color-commands/install
${BASE_DIR}/cursor/install
${BASE_DIR}/gcloud/install
${BASE_DIR}/gemini-cli/install
${BASE_DIR}/git/install
${BASE_DIR}/gradle/install
${BASE_DIR}/htop/install
${BASE_DIR}/ice/install
${BASE_DIR}/java/install
${BASE_DIR}/maven/install
${BASE_DIR}/node/install
${BASE_DIR}/python/install
${BASE_DIR}/vim/install
