#!/usr/bin/env zsh

BASE_DIR=$( cd $( dirname ${(%):-%x} ) &> /dev/null && pwd )

if [[ -s "${HOME}/.vimrc " ]]; then
    echo "Backing up .vimrc"
    cp -v ${HOME}/.vimrc ${HOME}/.vimrc.vim.bak
fi

echo "Installing .vimrc"
cp -v ${BASE_DIR}/vimrc ${HOME}/.vimrc