#!/usr/bin/env zsh
if [[ -s "${HOME}/.vimrc " ]]; then
    echo "Backing up .vimrc"
    cp -v ${HOME}/.vimrc ${HOME}/.vimrc.vim.bak
fi

echo "Uninstalling .vimrc"
rm -f ${HOME}/.vimrc

echo "Removing ~/.vim"
rm -rf ${HOME}/.vim