#!/usr/bin/env zsh
if command -v brew >/dev/null 2>&1; then
    brew uninstall antidote
fi

if [[ -d "${HOME}/Library/Caches/antidote" ]]; then
    echo "Removing ~/Library/Caches/antidote"
    rm -rf ${HOME}/Library/Caches/antidote
fi

if [[ -s "${HOME}/.zsh_plugins.zsh" ]]; then
    echo "Removing ~/.zsh_plugins.zsh"
    rm -f ${HOME}/.zsh_plugins.zsh
fi