#!/usr/bin/env bash

BASE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

if [[ -s "${HOME}/.tmux.conf " ]]; then
echo "Backing up .tmux.conf"
cp -v ${HOME}/.tmux.conf ${HOME}/.tmux.conf.tmux.bak
fi
echo "Installing .tmux.conf"
cp -v ${BASE_DIR}/tmux.conf ${HOME}/.tmux.conf