#!/usr/bin/env zsh

BASE_DIR=$( cd $( dirname ${(%):-%x} ) &> /dev/null && pwd )

if [[ -s "${HOME}/.tmux.conf " ]]; then
    echo "Backing up .tmux.conf"
    cp -v ${HOME}/.tmux.conf ${HOME}/.tmux.conf.tmux.bak
fi

echo "Installing .tmux.conf"
cp -v ${BASE_DIR}/tmux.conf ${HOME}/.tmux.conf