#!/usr/bin/env bash

if [[ -s "${HOME}/.tmux.conf " ]]; then
    echo "Backing up .tmux.conf"
    cp -v ${HOME}/.tmux.conf ${HOME}/.tmux.conf.tmux.bak
fi

echo "Uninstalling .tmux.conf"
rm -f ${HOME}/.tmux.conf