#!/usr/bin/env zsh

BASE_DIR=$( cd $( dirname ${(%):-%x} ) &> /dev/null && pwd )

if [[ -s "${HOME}/.bashrc " ]]; then
    echo "Backing up .zsh_plugins.txt"
    cp -v ${HOME}/.zsh_plugins.txt ${HOME}/.zsh_plugins.txt.zsh.bak
fi  

echo "Installing .zsh_plugins.txt"
cp -v ${BASE_DIR}/zsh_plugins.txt ${HOME}/.zsh_plugins.txt

if [[ -s "${HOME}/.zshrc " ]]; then
    echo "Backing up .zshrc"
    cp -v ${HOME}/.zshrc ${HOME}/.zshrc.zsh.bak
fi

echo "Installing .zshrc"
cp -v ${BASE_DIR}/zshrc ${HOME}/.zshrc

. ${HOME}/.zshrc