#!/usr/bin/env bash

echo "Backing up .zsh_plugins.txt"
cp -v ${HOME}/.zsh_plugins.txt ${HOME}/.zsh_plugins.txt.zsh.bak

echo "Uninstalling .zsh_plugins.txt"
rm -f ${HOME}/.zsh_plugins.txt

echo "Backing up .zshrc"
cp -v ${HOME}/.zshrc ${HOME}/.zshrc.zsh.bak

echo "Uninstalling .zshrc"
rm -f ${HOME}/.zshrc