#!/usr/bin/env zsh
if [[ -s "${HOME}/.zsh_plugins.txt " ]]; then
    echo "Backing up .zsh_plugins.txt"
    cp -v ${HOME}/.zsh_plugins.txt ${HOME}/.zsh_plugins.txt.zsh.bak
fi

echo "Uninstalling .zsh_plugins.txt"
rm -f ${HOME}/.zsh_plugins.txt

if [[ -s "${HOME}/.zshrc " ]]; then
    echo "Backing up .zshrc"
    cp -v ${HOME}/.zshrc ${HOME}/.zshrc.zsh.bak
fi

#echo "Uninstalling .zshrc"
#rm -f ${HOME}/.zshrc