#!/usr/bin/env bash
BASE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

if [[ -s "${HOME}/.bashrc " ]]; then
    echo "Backing up .bashrc"
    cp -v ${HOME}/.bashrc ${HOME}/.bashrc.bash.bak
fi

echo "Installing .bashrc"
cp -v ${BASE_DIR}/bashrc ${HOME}/.bashrc