#!/usr/bin/env bash

if command -v brew >/dev/null 2>&1; then
    brew install curl

    #export PATH="/opt/homebrew/opt/curl/bin:$PATH"
    #export CURL_CA_BUNDLE="/opt/homebrew/etc/openssl/cert.pem"
fi  